version: 2.1

workflows:
  deploy-teste:
    jobs:
      - teste

jobs:
  teste:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: 
          name: Compilando Projeto
          command: mvn clean install
      
      - run:
          name: Salvando as coisas
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

      - store_test_results:
          path: /home/circleci/project/test-results

