version: 2.1

workflows:
  deploy-teste:
    jobs:
      - teste

jobs:
  teste:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: 
          name: Compilando Projeto
          command: mvn clean install
      - store_test_results:
          path: /home/circleci/project/test-results

